"""empty message

Revision ID: 864213d27301
Revises: cc192cf6a225
Create Date: 2020-11-07 19:38:30.692756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864213d27301'
down_revision = 'cc192cf6a225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'private')
    # ### end Alembic commands ###
