"""otra migration

Revision ID: d409c171c396
Revises: 2209bc4c7955
Create Date: 2020-10-11 09:55:48.452595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd409c171c396'
down_revision = '2209bc4c7955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('groupId', sa.Integer(), nullable=True),
    sa.Column('notifiedUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['group.id'], ),
    sa.ForeignKeyConstraint(['notifiedUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.drop_constraint('message_groupId_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'groupId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('groupId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_groupId_fkey', 'message', 'group', ['groupId'], ['id'])
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
